services:
  data_php:
    build:
      context: ./data_php
      args:
        XDEBUG_MODE: ${XDEBUG_MODE:-off}
    volumes:
      - ${LOCAL_DATA_DIR:-../data}:/meteringdata:ro
      - ${SRC_ROOT:-../src}:/var/www/html/
      - ../conf:/var/www/html/conf
    command: tail -f /dev/null
    user: ${CURRENT_UID}
    restart: always
    network_mode: host
    environment:
      ENVIRONET_PLUGIN_CONF_DIR: 'conf/plugins'
      LOCAL_DATA_DIR: ${LOCAL_DATA_DIR:-}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
