version: "3.7"
services:
  dist_database:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_HOST_PORT:-5432}:5432
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    restart: always

  dist_php:
    build:
      context: ./php
      args:
        XDEBUG_MODE: ${XDEBUG_MODE:-off}
    volumes:
      - ../conf:/var/www/html/conf
      - ../data/export:/var/www/html/data/export
      - ${SRC_ROOT:-../src}/logs/php:/logs
      - ${SRC_ROOT:-../src}:/var/www/html/
      - dist_phpsocket:/var/run/php
    depends_on:
      - dist_database
    restart: always
    environment:
      ENVIRONET_HOST_CONF_DIR: ../conf
      ENVIRONET_TIMEZONE: ${ENVIRONET_TIMEZONE:-}
      ENVIRONET_DB_HOST: 'dist_database'
      ENVIRONET_DB_PORT: 5432
      ENVIRONET_DB_NAME: ${POSTGRES_DB}
      ENVIRONET_DB_USER: ${POSTGRES_USER}
      ENVIRONET_DB_PASSWORD: ${POSTGRES_PASSWORD}

  dist_apache:
    build:
      context: ./apache
    depends_on:
      - dist_php
      - dist_database
    ports:
      - ${HOST_PORT:-80}:80
    volumes:
      - ${SRC_ROOT:-../src}/logs/apache:/logs
      - ${SRC_ROOT:-../src}:/var/www/html
      - dist_phpsocket:/var/run/php
    restart: always

  dist_logrotate:
    image: blacklabelops/logrotate
    volumes:
      - ${SRC_ROOT:-../src}/logs:/logs
      - ../data/logrotate-status:/logrotate-status
    depends_on:
      - dist_php
      - dist_database
      - dist_apache
    environment:
      LOGS_DIRECTORIES: /logs
      LOGROTATE_INTERVAL: weekly
      LOGROTATE_COPIES: 10

volumes:
  dist_phpsocket:

networks:
  default:
    name: environet
