version: "3.7"
services:
  data_php:
    build:
      context: ./data_php
    volumes:
      - ${LOCAL_DATA_DIR:-../data}:/meteringdata:ro
      - ${SRC_ROOT:-../src}:/var/www/html/
      - ../conf/plugins:/var/www/html/conf/plugins
    command: tail -f /dev/null
    user: ${CURRENT_UID}
    restart: always
    network_mode: host
    environment:
      ENVIRONET_PLUGIN_CONF_DIR: 'conf/plugins'
      LOCAL_DATA_DIR: ${LOCAL_DATA_DIR-}
