version: "3.7"
services:
  dist_database:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-environet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-q3DW7Ptb}
      POSTGRES_DB: ${POSTGRES_DB:-environet}
    ports:
      - ${DB_HOST_PORT:-5432}:5432
    volumes:
      - dist_postgres_data:/var/lib/postgresql/data
    restart: always

  dist_php:
    build:
      context: ./php
    volumes:
      - ../conf:/var/www/html/conf
      - ${SRC_ROOT:-../src}/logs/php:/logs
      - ${SRC_ROOT:-../src}:/var/www/html/
      - dist_phpsocket:/var/run/php
    depends_on:
      - dist_database
    restart: always
    environment:
      ENVIRONET_HOST_CONF_DIR: ../conf
      ENVIRONET_TIMEZONE: ${ENVIRONET_TIMEZONE}
      ENVIRONET_DB_HOST: 'dist_database'
      ENVIRONET_DB_PORT: 5432
      ENVIRONET_DB_NAME: ${POSTGRES_DB:-environet}
      ENVIRONET_DB_USER: ${POSTGRES_USER:-environet}
      ENVIRONET_DB_PASSWORD: ${POSTGRES_PASSWORD:-q3DW7Ptb}

  dist_apache:
    build:
      context: ./apache
    depends_on:
      - dist_php
      - dist_database
    ports:
      - ${HOST_PORT:-80}:80
    volumes:
      - ${SRC_ROOT:-../src}/logs/apache:/logs
      - ${SRC_ROOT:-../src}:/var/www/html
      - dist_phpsocket:/var/run/php
    restart: always

volumes:
  dist_phpsocket:
  dist_postgres_data:

networks:
  default:
    name: environet
